"""empty message

Revision ID: 431af85ba452
Revises: 8daff96f3acb
Create Date: 2023-05-29 17:16:52.089544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431af85ba452'
down_revision = '8daff96f3acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos_planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('planetas_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('vehiculos_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos_vehiculos')
    op.drop_table('favoritos_planetas')
    # ### end Alembic commands ###
