"""empty message

Revision ID: d40a5cfc6def
Revises: c65c325bfca7
Create Date: 2023-05-26 18:20:15.709707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40a5cfc6def'
down_revision = 'c65c325bfca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('year_nacimiento', sa.String(length=10), nullable=False),
    sa.Column('color_de_ojos', sa.String(length=20), nullable=False),
    sa.Column('color_de_piel', sa.String(length=20), nullable=False),
    sa.Column('color_de_pelo', sa.String(length=20), nullable=False),
    sa.Column('Peso', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personas')
    # ### end Alembic commands ###
