"""empty message

Revision ID: fc94f9d61903
Revises: d40a5cfc6def
Create Date: 2023-05-26 19:09:35.765596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc94f9d61903'
down_revision = 'd40a5cfc6def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.Column('periodo_rotacion', sa.Integer(), nullable=False),
    sa.Column('periodo_orbital', sa.Integer(), nullable=False),
    sa.Column('gravedad', sa.String(length=60), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.Column('clima', sa.String(length=80), nullable=False),
    sa.Column('terreno', sa.String(length=100), nullable=False),
    sa.Column('superficie_liquida', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('clase', sa.String(length=120), nullable=False),
    sa.Column('constructor', sa.String(length=120), nullable=False),
    sa.Column('coste', sa.Integer(), nullable=False),
    sa.Column('longitud', sa.Integer(), nullable=False),
    sa.Column('tripulacion', sa.Integer(), nullable=False),
    sa.Column('pasajeros', sa.Integer(), nullable=False),
    sa.Column('velocidad_maxima', sa.Integer(), nullable=False),
    sa.Column('capacidad_carga', sa.Integer(), nullable=False),
    sa.Column('provisiones', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Integer(), nullable=False))
        batch_op.drop_column('Peso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Peso', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('peso')

    op.drop_table('vehiculos')
    op.drop_table('planetas')
    # ### end Alembic commands ###
